---
title: "Acerv_YII"
author: "AnaPalacioAndIsoppopers"
date: "April 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# General project set-up 

```{r libraries, results="hide"}

getwd()

# Get all libraries and sources required to run the script

library(dplyr)
library(plyr)
library(reshape2)
library(ggplot2)

# Import your data: 
Acer.data<-read.csv("Data_YII_4-16-17.csv") 
```

Graphs with ggplot

```{r Plots}

# Graph each treatment by Colony during each sampling point

YII_trea <- ggplot(Acer.data, aes (Time, Y.II., colour=factor(Colony)))
YII_trea + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  geom_jitter()+
  facet_wrap(~Treatment)

# Graph each treatment during each sampling point
YII_Tre2 <- ggplot(Acer.data, aes (Time, Y.II., colour=factor(Treatment)))
YII_Tre2 + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5)
# geom_jitter()+
# facet_wrap(~Time)
```


```{r StatsForTime4}
Time6<-Acer.data[which(Acer.data$Time==6), ]
  
Time6$Treatment <- factor(Time6$Treatment)
  
ANOVA_Y <- aov(Y.II.~Treatment*Colony, Time6)
summary(ANOVA_Y)
plot(ANOVA_Y)

TukeyHSD (aov(Y.II.~Treatment, Time6))

```
